apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::629356683825:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1OKGN7PTOCRD4
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-16T16:01:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1461"
  uid: c0a4d333-10e8-4bbb-8642-e9116869f5f9
